# Generated by Django 5.0.1 on 2024-01-29 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookapp', '0003_recipeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeproduct',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cookbookapp.recipe'),
            preserve_default=False,
        ),
    ]
