# Generated by Django 5.0.1 on 2024-01-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookapp', '0004_recipeproduct_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeproduct',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
