# Generated by Django 5.0.1 on 2024-01-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookapp', '0005_recipeproduct_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(through='cookbookapp.RecipeProduct', to='cookbookapp.product'),
        ),
    ]
